const data = {
  products: [
    {
      name: 'Afterglow',
      slug: 'duckchanel-keyboard-aterglow',
      category: 'Keyboard',
      img: '/images/p1.png',
      price: '100',
      countInStock: 10,
      brand: 'Ducky Chanel',
      rating: 4.5,
      numberReviews: 10,
      description: 'high quality keyboard',
    },
    {
      name: 'Deep Blue',
      slug: 'duckchanel-keyboard-deepblue',
      category: 'Keyboard',
      img: '/images/p2.png',
      price: '100',
      countInStock: 10,
      brand: 'Ducky Chanel',
      rating: 4.5,
      numberReviews: 10,
      description: 'high quality keyboard',
    },
    {
      name: 'Green Hyzen',
      slug: 'duckchanel-keyboard-green',
      category: 'Keyboard',
      img: '/images/p3.png',
      price: '100',
      countInStock: 10,
      brand: 'Ducky Chanel',
      rating: 4.5,
      numberReviews: 10,
      description: 'high quality keyboard',
    },
    {
      name: 'White Cow',
      slug: 'duckchanel-keyboard-white-cloud',
      category: 'Keyboard',
      img: '/images/p4.png',
      price: '100',
      countInStock: 10,
      brand: 'Ducky Chanel',
      rating: 4.5,
      numberReviews: 10,
      description: 'high quality keyboard',
    },
  ],
};

export default data;
