const data = {
  products: [
    {
      name: 'Honda CL50 Footer',
      slug: 'bamboo-motor-cl50-foot',
      category: 'Motor Detail',
      img: '/images/p1.png',
      price: '100',
      countInStock: 10,
      brand: 'L Bamboo',
      rating: 4,
      numberReviews: 10,
      description: 'high quality motor detail',
    },
    {
      name: 'Honda CD50 Footer',
      slug: 'bamboo-motor-cd50-foot',
      category: 'Motor Detail',
      img: '/images/p2.png',
      price: '100',
      countInStock: 0,
      brand: 'L Bamboo',
      rating: 3.5,
      numberReviews: 10,
      description: 'high quality motor detail',
    },
    {
      name: 'Honda SS50 Footer',
      slug: 'bamboo-motor-ss50-foot',
      category: 'Motor Detail',
      img: '/images/p3.png',
      price: '100',
      countInStock: 10,
      brand: 'L Bamboo',
      rating: 4.5,
      numberReviews: 10,
      description: 'high quality motor detail',
    },
    {
      name: 'Honda 66 Footer',
      slug: 'bamboo-motor-ss50-2-foot',
      category: 'Motor Detail',
      img: '/images/p4.png',
      price: '100',
      countInStock: 10,
      brand: 'L Bamboo',
      rating: 4.5,
      numberReviews: 10,
      description: 'high quality motor detail',
    },
  ],
};

export default data;
